### ISSUE TITLE
Transpiling with tsc instead babel in case of Jest

### ISSUE THREAD

**Issue by mucsi96** [damassi/babel-7-typescript-example#4]
First of all that's for creating this example and the blog post. It really helped me to solve the issues with TypeScript + Babel 7 + Jest in my new project https://github.com/mucsi96/nightwatch-api/tree/typescript

I am wondering why are you using `typescript-babel-jest` instead of `babel-jest`? As I can see the main idea of you setup is to use babel 7 to transpile TypeScript instead of tsc. 

I have checked the source of `typescript-babel-jest`. It looks like it is using `tsc` internally   https://github.com/lozinsky/typescript-babel-jest/blob/master/source/index.js#L13

This goes a little bit against of setup main goal. 

For me replacing `typescript-babel-jest` with `babel-jest` worked fine as well.
Also not sure why you need `babel-plugin-module-resolver`. Also works fine without it.

**Comment by damassi** [comment]
@mucsi96 - thanks! 

Re `typescript-babel-jest`, double thanks 👍 This was likely due to copy paste, will update. In the case of `babel-plugin-module-resolver` we use that all over internally so wanted to ensure that it worked here, and kept it in so that other projects have a template to copy from.
