### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by devth** [damassi/babel-7-typescript-example#6]
Hey thanks for sharing this awesome example. I used it as the basis of a new TS/Babel 7/React/Apollo Client project.

Any clue why the dependencies I've added on top of the ones you already setup (react and react-dom) result in `tsc` errors? I'm super confused by it.

```
src/components/Repl.tsx:2:21 - error TS2307: Cannot find module 'react-apollo'.

import {Query} from 'react-apollo';
                      ~~~~~~~~~~~~~~


src/components/Repl.tsx:3:17 - error TS2307: Cannot find module 'graphql-tag'.

import gql from 'graphql-tag';
                  ~~~~~~~~~~~~~


src/components/Repl.tsx:5:21 - error TS2307: Cannot find module 'bloomer'.

import {Title} from 'bloomer';
```

These libraries are even written in TypeScript and are present in my package.json `dependencies`. 🤔

**Comment by damassi** [comment]
Hi @devth - let me give it a look

**Comment by damassi** [comment]
Alright @devth, just pushed up a fix. Realized I was missing `"moduleResolution": "node"`! Thanks for the bug report 👍

**Comment by devth** [comment]
Awesome thanks for the fix! This cleared up tons of errors on my project. 💯
